### ISSUE TITLE
Train code

### ISSUE THREAD

**Issue by kimtaehyeong** [gladzhang/ART#6]
Hi @gladzhang,

Thanks for sharing and great work.

I want to custom train my data. When will the train code be completed?

**Comment by gladzhang** [comment]
Hi @kimtaehyeong 

Thanks for your interest in our work. We will update the new version including training codes as soon as possible. The expected date is close to the end of November, after the deadline of CVPR submission. We will provide the complete version based on BasicSR so that everyone can clone the repository to proceed training and testing. The old version will be pushed to another branch. 

Best wishes.

**Comment by kimtaehyeong** [comment]
Hi @gladzhang 

I'll be waiting, Thank you so much!

**Comment by yulunzhang** [comment]
Hi @kimtaehyeong

Thanks for your interest in our work. The full version of our code is ready now. 

If you have any other problem, please let us know. Thanks.

Best,
Yulun

**Comment by kimtaehyeong** [comment]
Hello @yulunzhang 
Thanks for the quick work.
I want to train in my custom data, but is there anything I need to pay attention to or change?

Thank you.

**Comment by yulunzhang** [comment]
Hi @kimtaehyeong 

For your own paired data, I think it's easy for you to use them. You can mainly follow a similar naming strategy as ours when preparing the data.

**Comment by kimtaehyeong** [comment]
Hello @yulunzhang
Let's try it.
Thank you for kindly letting us know.
